export const data = [
  {
    id: 0,
    title: "AVARIN",
    type: "VITRINE",
    year: "2023",
    src: [""],
    description: [
      "Avarin LTD, une jeune agence...",
      "Notre approche créative...",
      "",
      "",
    ],
    services: ["WEB DESIGN, ", "DEVELOPPEMENT, ", "PHOTOGRAPHIE"],
    stack: ["FIGMA, ", "ADOBE, "],
    link: "https://www.avarinltd.com",
  },
  {
    id: 1,
    title: "ACE CLOTHING",
    type: "E-COMMERCE",
    year: "2021",
    src: [""],
    description: [
      "ACE CLOTHING est une start-up de l’industrie textile qui savait que son audience était en ligne — mais son image n’y était pas encore. Leur ambition : capter une clientèle plus large grâce à une boutique e-commerce engageante, performante et visuellement forte. Nous avons conçu une présence digitale pensée pour la conversion, avec une direction artistique audacieuse, une identité visuelle stylisée et un site web fluide, parfaitement adapté aux standards du prêt-à-porter en ligne. Résultat : une marque qui sort du lot, portée par un univers visuel cohérent, du branding à la retouche photo.",
    ],
    services: [
      "WEB DESIGN, ",
      "DEVELOPPEMENT, ",
      "PHOTOGRAPHIE, ",
      "RETOUCHE PHOTO, ",
      "BRANDING, ",
      "DIRECTION ARTISTIQUE",
    ],
    stack: ["ADOBE, ", "HTML, ", "CSS, ", "FIGMA"],
    link: "https://www.ace-thestore.rf.gd",
  },
  {
    id: 2,
    title: "DIDUS ART",
    type: "ART",
    year: "2024",
    src: [""],
    description: [
      "DIDUS ART nous est arrivé avec un site web vieillissant et une présence sociale presque absente. Les photos mal cadrées et les visuels déconnectés de leur audience nuisaient à la qualité perçue de leur travail. Nous avons tout repensé — du design du site à l’univers visuel sur Instagram. Résultat : une marque artistique avec une image cohérente, professionnelle, et surtout, en phase avec les attentes esthétiques de sa communauté. Chaque élément visuel, chaque post, chaque pixel est désormais une vitrine de leur art.",
    ],
    services: [
      "WEB DESIGN, ",
      "DEVELOPPEMENT, ",
      "PHOTOGRAPHIE, ",
      "RETOUCHE PHOTO, ",
      "GRAPHIC DESIGN, ",
      "SMM",
    ],
    stack: ["ADOBE, ", "FIGMA, ", "REACT, ", "VITE, ", "JAVASCRIPT"],
    link: "didusart.com",
  },
  {
    id: 3,
    title: "LA MAISON DU SOLITAIRE",
    type: "E-COMMERCE",
    year: "2024",
    src: [""],
    description: [
      "Cette marque n’avait aucune empreinte digitale — pas de site, pas de canal d’acquisition en ligne. Elle voulait attirer de nouveaux clients sans dépendre uniquement du bouche-à-oreille. Ensemble, nous avons imaginé un site élégant, clair, centré sur l’histoire du produit et l’émotion de l’acte d’achat. Plus qu’un simple site vitrine, LA MAISON DU SOLITAIRE s’est dotée d’un point d’entrée stratégique vers un nouveau public, avec une esthétique minimaliste qui laisse briller l’essentiel : leur savoir-faire.",
    ],
    services: ["WEB DESIGN, ", "DEVELOPPEMENT"],
    stack: ["FIGMA, ", "REACT"],
    link: "https://www.lamaisondusolitaire.com",
  },
  {
    id: 4,
    title: "MY KEYS REALTY",
    type: "BUSINESS",
    year: "2023",
    src: [""],
    description: [
      "MY KEYS REALTY, c’est l’agence immobilière qui voulait moderniser son image sans perdre son ancrage local. Nous avons travaillé sur leur branding et leur présence sur les réseaux sociaux, en les dotant d’un logo contemporain, de visuels retouchés avec soin, et d’une stratégie de contenus pour attirer de nouveaux clients. C’est une immersion dans le neuf pour un secteur qui reste trop souvent figé. Leur nouvelle identité reflète une agence tournée vers l’avenir, connectée à ses prospects.",
    ],
    services: ["PHOTOGRAHIE, ", "SMM, ", "RETOUCHE PHOTO, ", "BRANDING"],
    stack: ["ADOBE"],
    link: "",
  },
  {
    id: 5,
    title: "RIVA EXCELLENCE",
    type: "E-COMMERCE",
    year: "2022",
    src: [""],
    description: [
      "RIVA EXCELLENCE, une boutique d’horlogerie à l’ancienne, a franchi le pas vers le numérique avec nous. L’objectif : ne pas perdre l’âme artisanale, mais la traduire dans un langage digital moderne. Nous avons repensé leur image, créé un site vitrine raffiné et soigné, et produit des visuels haut de gamme pour les réseaux sociaux. Chaque montre exposée en ligne raconte désormais une histoire — celle d’un artisanat intemporel, rendu accessible au public connecté d’aujourd’hui.",
    ],
    services: [
      "WEB DESIGN, ",
      "DEVELOPPEMENT, ",
      "PHOTOGRAPHIE",
      "RETOUCHE PHOTO",
      "GRAPHIC DESIGN",
      "SMM",
    ],
    stack: ["ADOBE, ", "FIGMA, ", "REACT, ", "JAVASCRIPT, "],
    link: "",
  },

  {
    id: 6,
    title: "GAMZELICIOUSS",
    type: "PHOTO",
    year: "2025",
    src: [""],
    description: [
      "GAMZELICIOUSS voulait passer à la vitesse supérieure sur Instagram. Fini les photos floues ou trop sombres — place à une direction artistique assumée, avec des shootings en extérieur, de la lumière naturelle et des retouches précises. Nous avons transformé leur feed en véritable portfolio visuel, pensé pour séduire, inspirer et engager. L’image devient outil stratégique, et chaque post devient une invitation à découvrir plus.",
    ],
    services: ["PHOTOGRAPHIE, ", "RETOUCHE PHOTO"],
    stack: ["ADOBE"],
    link: "",
  },
  {
    id: 7,
    title: "THE TYRE SHOP CO",
    type: "E-COMMERCE",
    year: "2024",
    src: ["/images/avarin1.webp"],
    description: [
      "THE TYRE SHOP CO, un commerce de pneus et de produits auto, voulait briser les murs de son magasin physique pour conquérir le web. Nous avons créé un site fonctionnel, clair, centré sur la facilité de navigation et la présentation produit. Le défi : rendre un univers technique accessible, tout en gardant une touche professionnelle. Grâce à ce nouveau canal digital, le commerce devient service — rapide, pratique, décentralisé.",
    ],
    services: ["WEB DESIGN, ", "DEVELOPPEMENT"],
    stack: ["FIGMA, ", "REACT, ", "JAVASCRIPT"],
    link: "https://www.thetyreshopco.com",
  },
]
