import type { Metadata } from "next"
import { neue } from "./fonts/fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased p-3 ${neue.className} text-[#f1f1f1] bg-black`}
      >
        {children}
      </body>
    </html>
  )
}
