import type { Metadata } from "next"
import "locomotive-scroll/dist/locomotive-scroll.css"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-black text-[#fffef4] p-4`}>
        {children}
      </body>
    </html>
  )
}
