export const MARQUEE_LABELS = [
  "01 CREER SANS LIMITES //",
  "02 ACCUEILLIR LE CHANGEMENT //",
  "03 REGARDER LOIN DEVANT //",
  "04 FAIRE QUE CA COMPTE //",
  "05 CHOISIR L'AVENIR //",
  "06 CHERCHER L'OMBRE",
]
